### ISSUE TITLE
Got this error with my token ids

### ISSUE THREAD

**Issue by CryptorClub** [RobertDaleSmith/twitter-comment-exporter#1]
`You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product'`

Thanks for developing this tool!
Would be happy, if you can suggest, how to fix it.

**Comment by RobertDaleSmith** [comment]
Unfortunately X removed these API endpoints from the free plan. I have not tried it yet but should work with the $100/m X dev app plan.

**Comment by CryptorClub** [comment]
> Unfortunately X removed these API endpoints from the free plan. I have not tried it yet but should work with the $100/m X dev app plan.

Thanks for answer and suggest!
